### ISSUE TITLE
Make work with Sidekiq 5

### ISSUE THREAD

**Issue by krisleech** [krisleech/wisper-sidekiq#11]
We need to stop using sidekiq's `#delay` method as this no longer works in Sidekiq 5, see: https://github.com/mperham/sidekiq/wiki/Delayed-extensions

Related to #7

**Comment by rromanchuk** [comment]
I think you mean sidekiq 5.x, Rails 5 and sidekiq 4.x work fine 😄

**Comment by rromanchuk** [comment]
btw, if anyone is reading this and needs to use `5.0` you can hack it back in with `Sidekiq::Extensions.enable_delay!` in your initializer until this is decoupled

**Comment by krisleech** [comment]
@rromanchuk Indeed that is what I meant, fixed. Thanks.

**Comment by krisleech** [comment]
If anyone fancies taking a stab at this please do, it should not be too tricky, I just don't have time right now.
It might even be best to copy/paste the `#delay` code from sidekiq < 5 in to the broadcaster so it works *exactly* the same as it always has.

**Comment by krisleech** [comment]
I have started work on this in branch `sidekiq5-compatibility`. It can be used with any version of sidekiq. If using Sidekiq 5 then `Sidekiq::Extensions.enable_delay!` is no longer needed.

Please report back any success/failures.

This change will also allow full control over how we interact with Sidekiq, allowing, for example, the queue to be specified, in a future PR.

**Comment by krisleech** [comment]
fixed in master
