### ISSUE TITLE
Is there a way to specify the queue for wisper events?

### ISSUE THREAD

**Issue by joegaudet** [krisleech/wisper-sidekiq#15]
Wisper pubs all get queued in the default queue, I'd prefer to be able to put them in their own queue.

**Comment by krisleech** [comment]
[The implementation](https://github.com/krisleech/wisper-sidekiq/blob/master/lib/wisper/sidekiq.rb#L9) uses the sidekiq `delay` method to send the job to the queue, thus using the default queue. 

I'd be open to a PR to make this configurable, something like:

```ruby
Wisper::Sidekiq.configure do |c|
  c.queue = "my-special-queue"
end
```

**Comment by krisleech** [comment]
I have started work on #11 which will make this work easier.

**Comment by krisleech** [comment]
fixed in master

**Comment by joegaudet** [comment]
@krisleech just found this, wondering how I queue them in a queue other than default?

**Comment by AndrewFreemantle** [comment]
Vote for re-open please.. if this is now possible given #16 then would you kindly provide an example?
