### ISSUE TITLE
NoMethodError: undefined method `set' for Wisper::SidekiqBroadcaster::Worker:Class

### ISSUE THREAD

**Issue by krisleech** [krisleech/wisper-sidekiq#20]
This happens with Sidekiq 2.x and 3.x

**Comment by krisleech** [comment]
I have added a constraint to gemspec, so that it depends on Sidekiq ~>4.0.

If you are using sidekiq < 4.0 then you should get the previous 0.1.0 version of wisper-sidekiq.

In order to prevent this happening again we need to run the specs with each version of sidekiq we want to support.

**Comment by krisleech** [comment]
Wisper 1.0.0 yanked.

**Comment by laertispappas** [comment]
@krisleech  How do you plan to handle backwards compatibility for older sidekiq versions? Running the specs locally I get a failing test for `uninitialized constant Sidekiq::Queues` as well.

**Comment by krisleech** [comment]
@laertispappas it is a good question, to which I have no answer yet.

The primary reason that we needed to make any changes was because Sidekiq 5.x removed the `#delay` method, or rather it became opt-in. Otherwise version 0.0.1 works with all versions of Sidekiq < 5. Version 1.x supports Sidekiq 5+. 

I'm not sure what the error you are getting is, which version of Sidekiq are you using?

Some potential options:

* a version per Sidekiq version, e.g. wisper-sidekiq 1.x support Sidekiq 1.x etc.
* We try and support all versions via branching inside a single version of wisper-sidekiq.

Any thoughts/help welcome.

**Comment by laertispappas** [comment]
@krisleech  Not sure. Since the code is pretty small I would go with `if else` statements instead and avoid maintaining different branches for now. Could I give it a try if I find some time?

**Comment by krisleech** [comment]
If we go with branching which I don't think is a bad choice we need to setup travis to test the code against each version of sidekiq using a separate Gemfile like [this](https://github.com/krisleech/wisper-activerecord/blob/master/.travis.yml).

**Comment by krisleech** [comment]
Worth noting the comments on https://github.com/krisleech/wisper-sidekiq/issues/21

**Comment by krisleech** [comment]
I've added a note to README about which version to use with which version of Sidekiq. Please feel free to reopen this issue if you want to submit a PR to make compatible with any version of Sidekiq.
