### ISSUE TITLE
ArgumentError: undefined class/module

### ISSUE THREAD

**Issue by imshenitsky** [krisleech/wisper-sidekiq#25]
With the following code and sidekiq 5.2.3, wisper-sidekiq 1.2.0
```ruby
class AudioQualifier
  def self.qualify(id)
  # ...

obj.subscribe(AudioQualifier, async: true) 
# ...

broadcast :qualify, id
# ...
```
I have errors
ArgumentError: undefined class/module AudioQualifier
Job `Wisper::SidekiqBroadcaster::Worker`

**Comment by krisleech** [comment]
Where is the exception raised?

**Comment by imshenitsky** [comment]
Here’s enqueued job through sidekiq web - http://prntscr.com/mrajh7
It's at Wisper::SidekiqBroadcaster::Worker
sidekiq log
```
2019-02-28T11:25:25.071Z 32994 TID-oup7ft9t6 Wisper::SidekiqBroadcaster::Worker JID-803980e3380f991c6587e4e4 INFO: fail: 0.043 sec
2019-02-28T11:25:25.071Z 32994 TID-oup7ft9t6 WARN: {"context":"Job raised exception","job":{"args":["---\n- !ruby/class 'AudioQualifier'\n- qualify\n- - 520\n"],"class":"Wisper::SidekiqBroadcaster::Worker","retry":true,"queue":"default","jid":"803980e3380f991c6587e4e4","created_at":1551353011.0865788,"enqueued_at":1551353011.0889878},"jobstr":"{\"args\":[\"---\\n- !ruby/class 'AudioQualifier'\\n- qualify\\n- - 520\\n\"],\"class\":\"Wisper::SidekiqBroadcaster::Worker\",\"retry\":true,\"queue\":\"default\",\"jid\":\"803980e3380f991c6587e4e4\",\"created_at\":1551353011.0865788,\"enqueued_at\":1551353011.0889878}"}
2019-02-28T11:25:25.071Z 32994 TID-oup7ft9t6 WARN: ArgumentError: undefined class/module AudioQualifier
```

**Comment by krisleech** [comment]
This doesn't look like an issue with Wisper. It looks like AudioQualifier is not loaded. I would suggest you try using AudioQualifier from inside a regular sidekiq worker using the [delay extension](https://github.com/mperham/sidekiq/wiki/Delayed-Extensions) which is what wisper mimics.

**Comment by imshenitsky** [comment]
Thanks for sharing, I use “delay” provided by sidekiq but for other aims. Audio Qualifier is a general AR model and loaded automatically. I actually interested in handle events async like [described here](https://github.com/krisleech/wisper/wiki/Handle-events-asynchronously)

**Comment by poyzn** [comment]
Hello Kris.

First of all thank you for you work.

But for some reason I can't make wisper-sidekiq functionality work on Rails 5.2 + sidekiq 6 (or 5) + Ruby 2.6.6. I've created a simple test rails app https://github.com/poyzn/wisper-sidekiq-test with minimum code.

I implemented both scenarios in the app to call async functions - via sidekiq worker call and via wisper-sidekiq broadcast.
In the app both actions fire when visiting root path of the app and it works with sidekiq worker, but with wisper-sidekiq it fails with an error `ArgumentError: undefined class/module MyListener`.

It seems that something wrong with class loading. I tried to config autoload_paths and eager_load_paths for the app, but without any luck. The only way wisper-sidekiq scenario works when I explicitly require listener class in `application.rb`

Requiring all listeners in `application.rb` is kind of weird practice, so I'd like to ask you for advice. 
Is the gem compatible with my stack? How could I make it work?

**Comment by imshenitsky** [comment]
So what’s the best way to make it worked with general Rails application?

**Comment by johnmfarrell1** [comment]
I had this exact issue also on Sidekiq 5. 
The fix for me was to add `Sidekiq::Extensions.enable_delay!` to the sidekiq initializer. 
Without this, sidekiq wont load alot of modules/classes/extensions necessary for using the delay extension so when sidekiq tries to perform the delayed job using the serialised yaml job details, it's not seeing the class/module (hence the error).
