### ISSUE TITLE
sidekiq_options documentation clarification

### ISSUE THREAD

**Issue by tirdadc** [krisleech/wisper-sidekiq#27]
I'm not sure where I'm supposed to specify these. The documentation mentions the subscriber, but I don't have a class for that.

Do I need to add a class method to my listener?

```
MyListener
  def self.sidekiq_options
    { queue: 'reporting' }
  end
end

```
Or is this something to be specified when subscribing to the listener (ie this class is considered the subscriber?):

```
publisher.subscribe(MyListener, async: true, queue: 'reporting')
```

or defined as a class method on that class?

**Comment by krisleech** [comment]
By subscriber it means listener. So the first example should work, did you find that it does not?

**Comment by tirdadc** [comment]
Yeah, unfortunately it still seems to put this in the default queue. Is it because we're using `delay_for`? I also tried specifying the queue param directly there (`delay_for(5.minutes, queue: :reporting)`) with no results.

```ruby
class MyListener
  def self.sidekiq_options
    { queue: :reporting }
  end

  def self.something_created(s_id)
    something = Something.find_by(s_id)
    if something.nil?
      self.delay_for(5.minutes).something_created(s_id)
    else
      OtherJob.perform_later(s_id)
    end   
  end
end

```

**Comment by krisleech** [comment]
What is happening is that `#something_created` will be run as a sidekiq job in the reporting queue, and in that job you are then firing off a second sidekiq job (by calling `#deploy_for` or `#perform_later`). You need to configure those second jobs to use the correct queue. Wisper has no control over what happens inside the job itself.

**Comment by krisleech** [comment]
As a side note you could also just do the waiting inside `#something_created` if the model does not yet exist, e.g.

```ruby
def find_something(id, try = 1)
     something = Something.find_by(id: id)

      if something.nil? && try < 10
        sleep(try * 2)
        something = fetch_something(id, try + 1)
      end

      something || raise("No something found for #{id} after #{try} tries");
end
```
