### ISSUE TITLE
Why not exec queue?

### ISSUE THREAD

**Issue by chip-and-dail** [krisleech/wisper-sidekiq#3]
I'm trying to make a small example. The queue is created, but it does not start. Why? I will describe the steps that you are doing, I think it will be easier. I hope for your help.
A. controller:
```ruby
class BooksController < ApplicationController
...
def create
    service = CreateBook.new
    service.subscribe(ActivityListener, async: true)
    service.on(:reserver_item_successfull) { |book| redirect_to book_path(book.id) }
    service.on(:reserver_item_failed)      { |book| @book = Book.new(book_params); respond_with(@book) }
    service.execute(current_user, book_params)
end
...
```
B. service:
```ruby
require 'wisper/sidekiq'
require 'sidekiq/api'

class CreateBook
  include Wisper::Publisher

  def execute(performer, attributes)
    book = Book.new(attributes)
    if book.valid?
      book.save
      broadcast(:reserver_item_successfull, performer, book)
    else
      broadcast(:book_failed, performer, book)
    end
  end
end
```

C. listener:
```ruby
class ActivityListener
  def self.reserver_item_successfull(performer, book)
    puts performer.name.to_s + ", book: " + book.title.to_s
  end
end
```

When I save the book, then of course creates a queue. But:
- sidekiq silent (the logs are empty, but the queue was created)
![2015-02-25 1 40 50](https://cloud.githubusercontent.com/assets/89529/6361007/a6004cc6-bc8f-11e4-856d-28dc3cfc20c4.png)
![2015-02-25 1 30 54](https://cloud.githubusercontent.com/assets/89529/6360819/2d71fe22-bc8e-11e4-8443-e29dd9b7cfef.png)
- redis silent too
![2015-02-25 1 43 33](https://cloud.githubusercontent.com/assets/89529/6361025/c1257a30-bc8f-11e4-9abf-ab245c30442e.png)

Maybe I'm wrong start redis (redis-server) or sidekiq (bundle exec sidekiq)? Please help me.

**Comment by krisleech** [comment]
Does Sidekiq work without Wisper, i.e. can you get a job to run on Sidekiq at all?
Are you sure that the event is being broadcast (i.e. the model is valid)?

**Comment by krisleech** [comment]
By the way doesn't the 3 enqueued jobs indicate it is working?

**Comment by chip-and-dail** [comment]
Sorry, misunderstood your question.
- Model is valid. Because we see that in Sidekiq is added to the task.
- If you turn off Sidekiq, the task is still queued.
- The jobs are very simple. Inside only puts.

If I change from this:
```
service.subscribe(ActivityListener, async: true)
``` 
to this:
```
service.subscribe(ActivityListener.new)
```

and from this:
```
def selft.reserver_item_successfull(performer, book)
```
to this:
```
def reserver_item_successfull(performer, book)
```

Then the method reserver_item_successfull works.

![2015-02-25 14 37 52](https://cloud.githubusercontent.com/assets/89529/6370001/bb0d41ec-bcfc-11e4-80e1-4f1bf143de34.png)


I think I got confused.

**Comment by chip-and-dail** [comment]
The problem is solved. I had to run sidekiq:
```
bundle exec sidekiq-r ./server.rb-L log/sidekiq.log
```

also in server.rb

```
require 'sidekiq'

Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://localhost:6379/0' }
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://localhost:6379/0' }
end
```

Sorry.

**Comment by krisleech** [comment]
Glad you got it sorted :smile:

**Comment by chip-and-dail** [comment]
Thanks. 

But now not running task. In sidekiq.log: ArgumentError: undefined class/module ActivityListener I added to application.rb string with eager_load_paths config, but not working. OOohhhhh.... I will solve...
