### ISSUE TITLE
Update documentation for Sidekiq 5 (enabled_delay)

### ISSUE THREAD

**Issue by julianajuliano** [krisleech/wisper-sidekiq#32]
It looks like it's necessary to configure the delay extension for wisper to work properly with Sidekiq 5

`Sidekiq::Extensions.enable_delay!`

It'd be good to add this to the documentation, it took me quite a while to find what was going on.

**Comment by cavi21** [comment]
@julianajuliano it seems that the delayed calls are using the `.perform_at` instead of the delay methods of the extension

**Comment by krisleech** [comment]
Please create a PR for a document update if needed, thanks!
