### ISSUE TITLE
Wisper Sidekiq Queueing

### ISSUE THREAD

**Issue by jfelchner** [krisleech/wisper-sidekiq#7]
@krisleech I wasn't sure where to put this but I figured this was the best place.

I have a question about how `wisper-sidekiq` works.  The code is extremely simple and I'd expect to see something along the lines of a `Sidekiq.push` somewhere.  But other than the `require` [here](https://github.com/krisleech/wisper-sidekiq/blob/master/lib/wisper/sidekiq.rb#L2), there's not even any reference to `sidekiq` anywhere.

So how does `wisper-sidekiq` queue the jobs?  I don't see it in the jobs anywhere and I don't know how to track down if the job fails (our normal jobs end up in the "Dead" queue).

Thanks!
PS: I'll be happy to update the README with your answer if you'd like.

**Comment by krisleech** [comment]
Hi - It uses the Sidekiq [delay](https://github.com/mperham/sidekiq/wiki/Delayed-extensions) method, which you will see here https://github.com/krisleech/wisper-sidekiq/blob/master/lib/wisper/sidekiq.rb#L9

**Comment by jfelchner** [comment]
@krisleech, thanks for responding.  I guess then _that's_ what I'm missing, where is the `subscriber` variable passed in inside `wisper`?  I'm just trying to figure out how `subscriber` becomes a `sidekiq` object.

**Comment by krisleech** [comment]
I believe the `delay` method which Sidekiq provides wraps the listener (receiver of `delay`) in a `DelayedClass`, see [here](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/extensions/class_methods.rb).
