### ISSUE TITLE
Honeybadger not starting

### ISSUE THREAD

**Issue by jeremyw** [krisleech/wisper-sidekiq#9]
I have a pretty simple Sinatra app using wisper-sidekiq. I'd like Honeybadger to be notified of exceptions raised in the worker, but it doesn't seem to be initialized (Honeybadger's `Agent` is not started).

Honeybadger is initialized correctly in Sinatra and handles exceptions raised synchronously.

Is there an idiomatic way to initialize Honeybadger so that it's initialized by the sidekiq worker?

**Comment by jeremyw** [comment]
I should also note that calling `Honeybadger.start` in a wisper subscriber also solves the problem, but that shouldn't be necessary.

**Comment by krisleech** [comment]
> Is there an idiomatic way to initialize Honeybadger so that it's initialized by the sidekiq worker?

This is a question for the Sidekiq and/or Honeybadger people. By the time an exception is raised in a worker it is out of the hands of Wisper.
